#! /bin/bash

while read S_USER S_DISPLAY; do
   DISPLAY="${S_DISPLAY}" \
       su "${S_USER}" \
           -m \
           -s /bin/bash \
           -c "/usr/bin/notify-send $(printf "%q " "$@")"
done < <(who | \
       awk '/:[0-9]+\.[0-9]+/ {
                print $1, $2;
            }')

