#! /bin/bash

# Folder to monitor
DIR=~/Downloads

# RPC connection settings
RPC_HOST=localhost:9091
RPC_AUTH=
RPC_EXEC=/usr/bin/transmission-remote
RPC_OPTS=



# Build RPC options
RPC_CALL="${RPC_EXEC} ${RPC_OPTS} ${RPC_HOST}"

if [ -n "${RPC_AUTH}" ]; then
				RPC_CALL="${RPC_CALL} --auth=$RPC_AUTH} "
fi


# Scan all .torrent files in watch folder
for FILE in ${DIR}/*.torrent; do
				# Add file to server
				${RPC_CALL} --add ${FILE}	

				# Remove file from local folder
				rm -f ${FILE}
done
