#! /bin/bash

[[ -z "${EDITOR}" ]] && EDITOR="/usr/bin/vim"

SEPARATOR=":"

if [ "x${1}" == "x" ]; then
	${EDITOR}
else
	FILE=$(echo ${1%${SEPARATOR}*})
	LINE=$(echo ${1#*${SEPARATOR}})
	
	if [ "x${FILE}" != "x${LINE}" ]; then
		${EDITOR} "${FILE}" "+${LINE}"
	else
		${EDITOR} "${FILE}"
	fi
fi
